# fly.toml app configuration file generated for autolog-api-icy-rain-1949 on 2025-05-05T22:47:32+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'autolog-api-icy-rain-1949'
primary_region = 'nrt'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
